CREATE TABLE IF NOT EXISTS sales_targets (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  external_id VARCHAR(120) NOT NULL,
  employee_id VARCHAR(120) NULL,
  employee_name VARCHAR(255) NULL,
  employee_code VARCHAR(120) NULL,
  period_type VARCHAR(20) NOT NULL,
  week_number INT NULL,
  month INT NULL,
  year INT NULL,
  revenue_target DECIMAL(18,2) NOT NULL DEFAULT 0,
  lead_target INT NOT NULL DEFAULT 0,
  quotation_target INT NOT NULL DEFAULT 0,
  conversion_target INT NOT NULL DEFAULT 0,
  collection_target DECIMAL(18,2) NOT NULL DEFAULT 0,
  renewal_target INT NOT NULL DEFAULT 0,
  notes TEXT NULL,
  payload JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_sales_targets_external_id (external_id),
  KEY idx_sales_targets_employee_period (employee_id, period_type),
  KEY idx_sales_targets_year_month_week (year, month, week_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sales_performance_snapshots (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  external_id VARCHAR(120) NOT NULL,
  snapshot_key VARCHAR(180) NOT NULL,
  employee_id VARCHAR(120) NULL,
  employee_name VARCHAR(255) NULL,
  period_type VARCHAR(20) NOT NULL,
  week_number INT NULL,
  month INT NULL,
  year INT NULL,
  target_json JSON NULL,
  achievement_json JSON NULL,
  payload JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_sales_performance_snapshots_external_id (external_id),
  UNIQUE KEY uk_sales_performance_snapshots_key (snapshot_key),
  KEY idx_sales_performance_snapshots_employee_period (employee_id, period_type),
  KEY idx_sales_performance_snapshots_year_month_week (year, month, week_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sales_incentive_rules (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  external_id VARCHAR(120) NOT NULL,
  rule_name VARCHAR(255) NOT NULL,
  min_achievement_percent DECIMAL(8,2) NOT NULL DEFAULT 100,
  max_achievement_percent DECIMAL(8,2) NULL,
  fixed_bonus DECIMAL(18,2) NOT NULL DEFAULT 0,
  commission_percent DECIMAL(8,2) NOT NULL DEFAULT 0,
  extra_bonus DECIMAL(18,2) NOT NULL DEFAULT 0,
  active TINYINT(1) NOT NULL DEFAULT 1,
  payload JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_sales_incentive_rules_external_id (external_id),
  KEY idx_sales_incentive_rules_active (active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sales_incentive_adjustments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  external_id VARCHAR(120) NOT NULL,
  employee_id VARCHAR(120) NULL,
  employee_name VARCHAR(255) NULL,
  period_type VARCHAR(20) NULL,
  month INT NULL,
  year INT NULL,
  amount DECIMAL(18,2) NOT NULL DEFAULT 0,
  note TEXT NULL,
  created_by VARCHAR(255) NULL,
  payload JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_sales_incentive_adjustments_external_id (external_id),
  KEY idx_sales_incentive_adjustments_employee_period (employee_id, period_type),
  KEY idx_sales_incentive_adjustments_year_month (year, month)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
