CREATE TABLE IF NOT EXISTS customers (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  external_id VARCHAR(80) NOT NULL,
  display_name VARCHAR(255) NULL,
  customer_name VARCHAR(255) NULL,
  company_name VARCHAR(255) NULL,
  contact_person_name VARCHAR(255) NULL,
  mobile_number VARCHAR(20) NULL,
  whatsapp_number VARCHAR(20) NULL,
  email_id VARCHAR(255) NULL,
  area_name VARCHAR(255) NULL,
  city VARCHAR(255) NULL,
  state VARCHAR(255) NULL,
  pincode VARCHAR(20) NULL,
  payload JSON NOT NULL,
  source_created_at DATETIME NULL,
  source_updated_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_customers_external_id (external_id),
  KEY idx_customers_mobile (mobile_number),
  KEY idx_customers_name (display_name, customer_name),
  KEY idx_customers_location (area_name, city, state, pincode)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS employees (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  external_id VARCHAR(80) NOT NULL,
  emp_code VARCHAR(80) NULL,
  first_name VARCHAR(255) NULL,
  last_name VARCHAR(255) NULL,
  role VARCHAR(120) NULL,
  role_name VARCHAR(255) NULL,
  mobile VARCHAR(20) NULL,
  email VARCHAR(255) NULL,
  city VARCHAR(255) NULL,
  pincode VARCHAR(20) NULL,
  payload JSON NOT NULL,
  source_created_at DATETIME NULL,
  source_updated_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_employees_external_id (external_id),
  KEY idx_employees_emp_code (emp_code),
  KEY idx_employees_role (role),
  KEY idx_employees_mobile (mobile)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS leads (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  external_id VARCHAR(80) NOT NULL,
  lead_date DATE NULL,
  customer_name VARCHAR(255) NULL,
  display_name VARCHAR(255) NULL,
  company_name VARCHAR(255) NULL,
  contact_person_name VARCHAR(255) NULL,
  title VARCHAR(255) NULL,
  mobile VARCHAR(20) NULL,
  whatsapp_number VARCHAR(20) NULL,
  email_id VARCHAR(255) NULL,
  address TEXT NULL,
  area_name VARCHAR(255) NULL,
  city VARCHAR(255) NULL,
  state VARCHAR(255) NULL,
  pincode VARCHAR(20) NULL,
  pest_issue VARCHAR(255) NULL,
  quotation_value DECIMAL(18,2) NULL,
  lead_source VARCHAR(120) NULL,
  lead_status VARCHAR(120) NULL,
  assigned_to VARCHAR(255) NULL,
  followup_date DATE NULL,
  google_place_id VARCHAR(255) NULL,
  google_place_name VARCHAR(255) NULL,
  google_phone VARCHAR(50) NULL,
  google_website VARCHAR(255) NULL,
  latitude DECIMAL(10,8) NULL,
  longitude DECIMAL(11,8) NULL,
  payload JSON NOT NULL,
  source_created_at DATETIME NULL,
  source_updated_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_leads_external_id (external_id),
  KEY idx_leads_mobile (mobile),
  KEY idx_leads_status (lead_status),
  KEY idx_leads_location (area_name, city, state, pincode),
  KEY idx_leads_place (google_place_id),
  KEY idx_leads_geo (latitude, longitude)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS invoices (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  external_id VARCHAR(80) NOT NULL,
  customer_external_id VARCHAR(80) NULL,
  customer_name VARCHAR(255) NULL,
  invoice_number VARCHAR(120) NULL,
  invoice_type VARCHAR(80) NULL,
  invoice_status VARCHAR(80) NULL,
  invoice_date DATE NULL,
  due_date DATE NULL,
  total_amount DECIMAL(18,2) NULL,
  balance_due DECIMAL(18,2) NULL,
  payload JSON NOT NULL,
  source_created_at DATETIME NULL,
  source_updated_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_invoices_external_id (external_id),
  KEY idx_invoices_number (invoice_number),
  KEY idx_invoices_customer_external (customer_external_id),
  KEY idx_invoices_dates (invoice_date, due_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS invoice_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  invoice_external_id VARCHAR(80) NOT NULL,
  line_index INT NOT NULL DEFAULT 0,
  item_id VARCHAR(80) NULL,
  item_name VARCHAR(255) NULL,
  description TEXT NULL,
  quantity DECIMAL(12,2) NULL,
  rate DECIMAL(18,2) NULL,
  tax_rate DECIMAL(8,2) NULL,
  amount DECIMAL(18,2) NULL,
  payload JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_invoice_items_line (invoice_external_id, line_index),
  KEY idx_invoice_items_invoice (invoice_external_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS jobs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  external_id VARCHAR(80) NOT NULL,
  customer_external_id VARCHAR(80) NULL,
  invoice_external_id VARCHAR(80) NULL,
  customer_name VARCHAR(255) NULL,
  job_number VARCHAR(120) NULL,
  status VARCHAR(120) NULL,
  service_name VARCHAR(255) NULL,
  service_type VARCHAR(120) NULL,
  area_name VARCHAR(255) NULL,
  city VARCHAR(255) NULL,
  state VARCHAR(255) NULL,
  pincode VARCHAR(20) NULL,
  scheduled_date DATE NULL,
  scheduled_time VARCHAR(40) NULL,
  payload JSON NOT NULL,
  source_created_at DATETIME NULL,
  source_updated_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_jobs_external_id (external_id),
  KEY idx_jobs_number (job_number),
  KEY idx_jobs_customer_external (customer_external_id),
  KEY idx_jobs_invoice_external (invoice_external_id),
  KEY idx_jobs_location (area_name, city, state, pincode)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS attendance (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  external_id VARCHAR(80) NOT NULL,
  employee_external_id VARCHAR(80) NULL,
  employee_code VARCHAR(80) NULL,
  employee_name VARCHAR(255) NULL,
  attendance_date DATE NULL,
  status VARCHAR(80) NULL,
  check_in TIME NULL,
  check_out TIME NULL,
  working_hours DECIMAL(8,2) NULL,
  payload JSON NOT NULL,
  source_created_at DATETIME NULL,
  source_updated_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_attendance_external_id (external_id),
  KEY idx_attendance_emp_date (employee_external_id, attendance_date),
  KEY idx_attendance_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS quotation_template_settings (
  id INT NOT NULL AUTO_INCREMENT,
  logo_url TEXT NULL,
  logo_width INT DEFAULT 90,
  logo_height INT DEFAULT 70,
  header_alignment VARCHAR(20) DEFAULT 'left',
  company_name VARCHAR(255) DEFAULT '',
  company_address TEXT NULL,
  phone VARCHAR(50) DEFAULT '',
  email VARCHAR(255) DEFAULT '',
  website VARCHAR(255) DEFAULT '',
  gstin VARCHAR(64) DEFAULT '',
  header_line_color VARCHAR(20) DEFAULT '#9F174D',
  primary_color VARCHAR(20) DEFAULT '#9F174D',
  border_color VARCHAR(20) DEFAULT '#cbd5e1',
  font_family VARCHAR(80) DEFAULT 'Helvetica',
  font_size INT DEFAULT 10,
  heading_font_size INT DEFAULT 14,
  body_font_size INT DEFAULT 10,
  table_font_size INT DEFAULT 9,
  footer_text TEXT NULL,
  signature_image_url TEXT NULL,
  default_sales_person VARCHAR(255) DEFAULT '',
  default_designation VARCHAR(255) DEFAULT '',
  default_mobile VARCHAR(50) DEFAULT '',
  show_logo TINYINT(1) DEFAULT 1,
  show_gstin TINYINT(1) DEFAULT 1,
  show_signature TINYINT(1) DEFAULT 1,
  show_page_number TINYINT(1) DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS quotation_prefix_settings (
  id INT NOT NULL AUTO_INCREMENT,
  prefix VARCHAR(50) DEFAULT 'SPC/',
  financial_year VARCHAR(20) DEFAULT '',
  enable_service_code TINYINT(1) DEFAULT 1,
  next_number INT DEFAULT 1,
  padding_digits INT DEFAULT 4,
  format_template VARCHAR(255) DEFAULT '{{prefix}}{{year}}/{{service_code}}/{{number}}',
  service_code_map_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS quotation_service_templates (
  id INT NOT NULL AUTO_INCREMENT,
  service_name VARCHAR(255) NOT NULL,
  service_code VARCHAR(30) DEFAULT '',
  pest_name VARCHAR(255) DEFAULT '',
  quotation_title VARCHAR(255) DEFAULT '',
  about_pest TEXT NULL,
  what_we_do TEXT NULL,
  treatment_points TEXT NULL,
  default_infestation_level VARCHAR(100) DEFAULT '',
  default_frequency VARCHAR(120) DEFAULT '',
  default_recommendation TEXT NULL,
  default_gst_percentage DECIMAL(10,2) DEFAULT 18,
  default_rate_without_gst DECIMAL(12,2) DEFAULT 0,
  default_rate_with_gst DECIMAL(12,2) DEFAULT 0,
  warranty_note TEXT NULL,
  service_terms TEXT NULL,
  is_active TINYINT(1) DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_quotation_service_templates_active (is_active, service_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS quotation_common_paragraphs (
  id INT NOT NULL AUTO_INCREMENT,
  opening_paragraph TEXT NULL,
  closing_paragraph TEXT NULL,
  payment_terms TEXT NULL,
  general_terms TEXT NULL,
  warranty_paragraph TEXT NULL,
  disclaimer_paragraph TEXT NULL,
  relationship_closing_paragraph TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS infestation_levels (
  id INT NOT NULL AUTO_INCREMENT,
  level_name VARCHAR(100) NOT NULL,
  description TEXT NULL,
  recommendation_text TEXT NULL,
  image_url TEXT NULL,
  sort_order INT DEFAULT 0,
  is_active TINYINT(1) DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_infestation_levels_sort (sort_order, level_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS quotations (
  id INT NOT NULL AUTO_INCREMENT,
  quotation_number VARCHAR(120) NOT NULL,
  source_type VARCHAR(40) DEFAULT 'Manual',
  lead_id VARCHAR(80) NULL,
  customer_id VARCHAR(80) NULL,
  customer_name VARCHAR(255) DEFAULT '',
  company_name VARCHAR(255) DEFAULT '',
  address TEXT NULL,
  phone VARCHAR(50) DEFAULT '',
  whatsapp VARCHAR(50) DEFAULT '',
  email VARCHAR(255) DEFAULT '',
  gstin VARCHAR(64) DEFAULT '',
  quotation_date DATE NULL,
  validity_days INT DEFAULT 15,
  prepared_by VARCHAR(255) DEFAULT '',
  sales_person VARCHAR(255) DEFAULT '',
  designation VARCHAR(255) DEFAULT '',
  mobile VARCHAR(50) DEFAULT '',
  contract_start_date DATE NULL,
  contract_end_date DATE NULL,
  subtotal_without_gst DECIMAL(12,2) DEFAULT 0,
  gst_total DECIMAL(12,2) DEFAULT 0,
  round_off DECIMAL(12,2) DEFAULT 0,
  grand_total DECIMAL(12,2) DEFAULT 0,
  amount_in_words TEXT NULL,
  rate_type VARCHAR(40) DEFAULT 'With GST',
  status VARCHAR(40) DEFAULT 'Draft',
  opening_paragraph TEXT NULL,
  payment_terms TEXT NULL,
  warranty_note TEXT NULL,
  disclaimer TEXT NULL,
  closing_paragraph TEXT NULL,
  internal_note TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_quotation_number (quotation_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS quotation_items (
  id INT NOT NULL AUTO_INCREMENT,
  quotation_id INT NOT NULL,
  service_template_id INT NULL,
  service_name VARCHAR(255) DEFAULT '',
  service_code VARCHAR(30) DEFAULT '',
  pest_name VARCHAR(255) DEFAULT '',
  service_title VARCHAR(255) DEFAULT '',
  about_pest TEXT NULL,
  what_we_do TEXT NULL,
  treatment_points TEXT NULL,
  infestation_level VARCHAR(100) DEFAULT '',
  infestation_image_url TEXT NULL,
  frequency VARCHAR(120) DEFAULT '',
  recommendation TEXT NULL,
  area_covered VARCHAR(255) DEFAULT '',
  quantity DECIMAL(12,2) DEFAULT 1,
  rate_without_gst DECIMAL(12,2) DEFAULT 0,
  gst_percentage DECIMAL(10,2) DEFAULT 18,
  gst_amount DECIMAL(12,2) DEFAULT 0,
  rate_with_gst DECIMAL(12,2) DEFAULT 0,
  total_amount DECIMAL(12,2) DEFAULT 0,
  contract_start_date DATE NULL,
  contract_end_date DATE NULL,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_quotation_items_quotation_id (quotation_id),
  CONSTRAINT fk_quotation_items_quotation FOREIGN KEY (quotation_id) REFERENCES quotations(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
