CREATE TABLE IF NOT EXISTS customers (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  external_id VARCHAR(80) NOT NULL,
  display_name VARCHAR(255) NULL,
  customer_name VARCHAR(255) NULL,
  company_name VARCHAR(255) NULL,
  contact_person_name VARCHAR(255) NULL,
  mobile_number VARCHAR(20) NULL,
  whatsapp_number VARCHAR(20) NULL,
  email_id VARCHAR(255) NULL,
  area_name VARCHAR(255) NULL,
  city VARCHAR(255) NULL,
  state VARCHAR(255) NULL,
  pincode VARCHAR(20) NULL,
  payload JSON NOT NULL,
  source_created_at DATETIME NULL,
  source_updated_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_customers_external_id (external_id),
  KEY idx_customers_mobile (mobile_number),
  KEY idx_customers_name (display_name, customer_name),
  KEY idx_customers_location (area_name, city, state, pincode)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS employees (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  external_id VARCHAR(80) NOT NULL,
  emp_code VARCHAR(80) NULL,
  first_name VARCHAR(255) NULL,
  last_name VARCHAR(255) NULL,
  role VARCHAR(120) NULL,
  role_name VARCHAR(255) NULL,
  mobile VARCHAR(20) NULL,
  email VARCHAR(255) NULL,
  city VARCHAR(255) NULL,
  pincode VARCHAR(20) NULL,
  payload JSON NOT NULL,
  source_created_at DATETIME NULL,
  source_updated_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_employees_external_id (external_id),
  KEY idx_employees_emp_code (emp_code),
  KEY idx_employees_role (role),
  KEY idx_employees_mobile (mobile)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS leads (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  external_id VARCHAR(80) NOT NULL,
  lead_date DATE NULL,
  customer_name VARCHAR(255) NULL,
  display_name VARCHAR(255) NULL,
  company_name VARCHAR(255) NULL,
  contact_person_name VARCHAR(255) NULL,
  title VARCHAR(255) NULL,
  mobile VARCHAR(20) NULL,
  whatsapp_number VARCHAR(20) NULL,
  email_id VARCHAR(255) NULL,
  address TEXT NULL,
  area_name VARCHAR(255) NULL,
  city VARCHAR(255) NULL,
  state VARCHAR(255) NULL,
  pincode VARCHAR(20) NULL,
  pest_issue VARCHAR(255) NULL,
  quotation_value DECIMAL(18,2) NULL,
  lead_source VARCHAR(120) NULL,
  lead_status VARCHAR(120) NULL,
  assigned_to VARCHAR(255) NULL,
  followup_date DATE NULL,
  google_place_id VARCHAR(255) NULL,
  google_place_name VARCHAR(255) NULL,
  google_phone VARCHAR(50) NULL,
  google_website VARCHAR(255) NULL,
  latitude DECIMAL(10,8) NULL,
  longitude DECIMAL(11,8) NULL,
  payload JSON NOT NULL,
  source_created_at DATETIME NULL,
  source_updated_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_leads_external_id (external_id),
  KEY idx_leads_mobile (mobile),
  KEY idx_leads_status (lead_status),
  KEY idx_leads_location (area_name, city, state, pincode),
  KEY idx_leads_place (google_place_id),
  KEY idx_leads_geo (latitude, longitude)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS invoices (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  external_id VARCHAR(80) NOT NULL,
  customer_external_id VARCHAR(80) NULL,
  customer_name VARCHAR(255) NULL,
  invoice_number VARCHAR(120) NULL,
  invoice_type VARCHAR(80) NULL,
  invoice_status VARCHAR(80) NULL,
  invoice_date DATE NULL,
  due_date DATE NULL,
  total_amount DECIMAL(18,2) NULL,
  balance_due DECIMAL(18,2) NULL,
  payload JSON NOT NULL,
  source_created_at DATETIME NULL,
  source_updated_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_invoices_external_id (external_id),
  KEY idx_invoices_number (invoice_number),
  KEY idx_invoices_customer_external (customer_external_id),
  KEY idx_invoices_dates (invoice_date, due_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS invoice_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  invoice_external_id VARCHAR(80) NOT NULL,
  line_index INT NOT NULL DEFAULT 0,
  item_id VARCHAR(80) NULL,
  item_name VARCHAR(255) NULL,
  description TEXT NULL,
  quantity DECIMAL(12,2) NULL,
  rate DECIMAL(18,2) NULL,
  tax_rate DECIMAL(8,2) NULL,
  amount DECIMAL(18,2) NULL,
  payload JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_invoice_items_line (invoice_external_id, line_index),
  KEY idx_invoice_items_invoice (invoice_external_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS jobs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  external_id VARCHAR(80) NOT NULL,
  customer_external_id VARCHAR(80) NULL,
  invoice_external_id VARCHAR(80) NULL,
  customer_name VARCHAR(255) NULL,
  job_number VARCHAR(120) NULL,
  status VARCHAR(120) NULL,
  service_name VARCHAR(255) NULL,
  service_type VARCHAR(120) NULL,
  area_name VARCHAR(255) NULL,
  city VARCHAR(255) NULL,
  state VARCHAR(255) NULL,
  pincode VARCHAR(20) NULL,
  scheduled_date DATE NULL,
  scheduled_time VARCHAR(40) NULL,
  payload JSON NOT NULL,
  source_created_at DATETIME NULL,
  source_updated_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_jobs_external_id (external_id),
  KEY idx_jobs_number (job_number),
  KEY idx_jobs_customer_external (customer_external_id),
  KEY idx_jobs_invoice_external (invoice_external_id),
  KEY idx_jobs_location (area_name, city, state, pincode)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS attendance (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  external_id VARCHAR(80) NOT NULL,
  employee_external_id VARCHAR(80) NULL,
  employee_code VARCHAR(80) NULL,
  employee_name VARCHAR(255) NULL,
  attendance_date DATE NULL,
  status VARCHAR(80) NULL,
  check_in TIME NULL,
  check_out TIME NULL,
  working_hours DECIMAL(8,2) NULL,
  payload JSON NOT NULL,
  source_created_at DATETIME NULL,
  source_updated_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_attendance_external_id (external_id),
  KEY idx_attendance_emp_date (employee_external_id, attendance_date),
  KEY idx_attendance_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
