const mongoose = require('mongoose');

const settingSchema = new mongoose.Schema({
  companyName: String,
  companyAddress: String,
  companyCity: String,
  companyState: String,
  companyPincode: String,
  companyGstNumber: String,
  companyEmail: String,
  companyMobile: String,
  companyWebsite: String,
  googleReviewLink: String,
  aboutTagline: String,
  companyServices: String,
  nonGstCompanyName: String,
  nonGstAddress: String,
  nonGstState: String,
  nonGstPincode: String,
  termsAndConditionsDefault: String,
  gstTermsAndConditions: String,
  nonGstTermsAndConditions: String,
  settingsAccessPin: String,
  invoicePrefix: String,
  invoiceNumberMode: String,
  invoiceNextNumber: Number,
  invoiceNumberPadding: Number,
  jobPrefix: String,
  jobNextNumber: Number,
  jobNumberPadding: Number,
  invoiceTemplate: String,
  invoiceVisibleColumns: [String],
  invoiceFieldSettings: mongoose.Schema.Types.Mixed,
  smtpHost: String,
  smtpPort: Number,
  smtpSenderName: String,
  smtpEncryption: String,
  smtpActive: String,
  smtpSecure: Boolean,
  smtpUser: String,
  smtpPass: String,
  smtpFromEmail: String,
  smtpTestTargetEmail: String,
  whatsappApiVersion: String,
  whatsappPhoneNumber: String,
  whatsappInstanceId: String,
  whatsappPhoneNumberId: String,
  whatsappAccessToken: String,
  whatsappContractExpiryToOwner: String,
  whatsappContractExpiryToCustomer: String,
  whatsappLeadFollowupToOwner: String,
  whatsappLeadFollowupToCustomer: String,
  whatsappLoginAlertToOwner: String,
  whatsappLoginAlertToCustomer: String,
  whatsappBusinessDigestToOwner: String,
  whatsappBusinessDigestToCustomer: String,
  dashboardImageUrl: String,
});

module.exports = mongoose.model('Setting', settingSchema);
